---

- name: configure openshift namespace
  hosts: localhost
  gather_facts: false
  tasks:
  - name: create namespace for cssr
    kubernetes.core.k8s:
      name: "{{ cssr_namespace }}"
      api_version: v1
      kind: Namespace
      state: present

  - name: deploy network attachments to openshift namespace
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
    loop: "{{ cssr_network_attachments }}"
