---

- name: deploy juniper cssr to openshift
  hosts: localhost
  gather_facts: false
  tasks:
  - name: create salt minion id configmap
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', 'cm-salt_minion_id.yaml.j2') | from_yaml }}"

  - name: create cssr preferences configmap
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', 'cm-preferences.yaml.j2') | from_yaml }}"

  - name: deploy cssr pod to openshift namespace
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', 'cssr-5121-auto.yaml.j2') | from_yaml }}"

  - name: get pod status
    kubernetes.core.k8s_info:
      kind: Pod
      label_selectors:
        - app = {{ cssr_name | lower }}
      field_selectors:
      - status.phase=Running
      namespace: "{{ cssr_namespace }}"
    register: pod_status
    until: 'pod_status.resources | length > 0'
    retries: 5
    delay: 5

  - name: stop 128T service
    kubernetes.core.k8s_exec:
      namespace: "{{ cssr_namespace }}"
      pod: "{{ cssr_name | lower }}"
      command: systemctl stop 128T

  - name: initialise cssr pod
    kubernetes.core.k8s_exec:
      namespace: "{{ cssr_namespace }}"
      pod: "{{ cssr_name | lower }}"
      command: initialize128t --preferences /etc/preferences.json

  - name: start salt minion in pod
    kubernetes.core.k8s_exec:
      namespace: "{{ cssr_namespace }}"
      pod: "{{ cssr_name | lower }}"
      command: systemctl restart salt-minion

  - name: start 128T service
    kubernetes.core.k8s_exec:
      namespace: "{{ cssr_namespace }}"
      pod: "{{ cssr_name | lower }}"
      command: systemctl start 128T
